project:
  type: website

website:
  title: "Quarto_mysite"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - hoge.qmd

format:
  html:
    theme: lumen
    css: styles.css
    toc: true
